linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style

run:
  timeout: 2m
